
repos:
-   repo: git@github.com:pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    - id: debug-statements
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: check-ast
    - id: check-merge-conflict
    - id: check-yaml
    - id: flake8
      args: ['--exclude=docs/*', '--ignore=E501,W503,E203']

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.9.1
  hooks:
  - id: isort
    additional_dependencies: ['toml']

- repo: https://github.com/python/black
  rev: 21.6b0
  hooks:
    - id: black
